#!/usr/bin/env python
import sys
from oslo.config import cfg
import traceback
import eventlet
eventlet.monkey_patch()

from energy.common import config
from energy.common import log
from energy import service

#energy_sampler_opts = [
#    cfg.StrOpt('sampler_config',
#                default='/etc/energy/energy-sampler.conf',
#                help='The configure file contains paramters of sampling data.',
#               ),
#]
#CONF = cfg.CONF
#CONF.register_opts(energy_sampler_opts, group='sampler')

LOG = log.getLogger(__name__)

if __name__ == "__main__":


    try:

        config.parse_args(sys.argv[1:])
        log.setup('energy-sampler')
        LOG.debug("Start Energy Sampler Service")

        server = service.Service.create()
        service.serve(server)
        service.wait()
    except Exception,e:
        traceback.print_exc()
