#!/usr/bin/python
import sys
import traceback
from energy.common import config
from energy.common import log
from oslo.config import cfg

from energy.db import api as db_api
from energy.db import migration


CONF = cfg.CONF

db_opts = [
    cfg.IntOpt('db_version',
                metavar='DBVERSION',
                default=2,
                help='init table of energy')
]
CONF.register_cli_opts(db_opts)

if __name__=="__main__":
    try:
        config.parse_args(sys.argv[1:])
        log.setup('energy-manager')
        print(migration.db_version())
        migration.db_sync(CONF.db_version)
        print(CONF.db_version)
        
    except Exception,e:
        traceback.print_exc()
